version: "3.4"

services:
  search-engine-db:
    image: postgres:11.6
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: restapi_dev
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
    ports:
      - 5453:5432
